/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_hotel;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Connection conexion;
    Statement sentencia;
    DefaultTableModel tablaGrupo;
    String consulta;
    
    /**
     * Creates new form NewJFrame_Main
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        PrepararBaseDatos();
    }
    
    void PrepararBaseDatos(){
        try{ //preparar carga del controlador
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            JOptionPane.showMessageDialog(null,"Carga del controlador: OK");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Carga del controlador: ERROR");
        }
        try{
            String URL="jdbc:sqlserver://DESKTOP-G4VPJTK\\SQLEXPRESS:1433;databaseName=GestionHotel;user=david;password=123456";
            conexion=DriverManager.getConnection(URL);
            JOptionPane.showMessageDialog(null,"Conexion con base de datos: OK");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Conexion con base de datos: ERROR");
        }
        try{
            sentencia =conexion.createStatement(
            ResultSet.TYPE_SCROLL_INSENSITIVE,
            ResultSet.CONCUR_READ_ONLY
          );
        JOptionPane.showMessageDialog(null,"Creacion del Objeto sentencia: OK");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Creacion del Objeto sentencia: ERROR");
        }
        
        String Etiqueta[]={"HabitacionID","NumeroHabitacion","Tipo","PrecioPorNoche","Estado"};
        tablaGrupo=new DefaultTableModel(null,Etiqueta);
        jTable1.setModel(tablaGrupo);
        
        tablaGrupo=(DefaultTableModel) jTable1.getModel();
        tablaGrupo.setRowCount(0);
        
        int j=1;
        
        try{
            ResultSet Res= sentencia.executeQuery("select *from Habitaciones");
            while(Res.next()){
                Vector VectorGrupo =new Vector();
                VectorGrupo.add(Res.getString("HabitacionID"));
                VectorGrupo.add(Res.getString("NumeroHabitacion"));
                VectorGrupo.add(Res.getString("Tipo"));
                VectorGrupo.add(Res.getString("PrecioPorNoche"));
                VectorGrupo.add(Res.getString("Estado"));
                tablaGrupo.addRow(VectorGrupo);
                jTable1.setModel(tablaGrupo);
                j++;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null," ERROR CARGAR LA TABLA");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
